# https://pre-commit.com/#installation
default_stages: [pre-commit, pre-push]
default_language_version:
  python: python3
  node: 24.11.1
minimum_pre_commit_version: '3.2.0'
repos:
  - repo: meta
    hooks:
      - id: identity
        name: Run identity
        description: Run the identity check
      - id: check-hooks-apply
        name: Check hooks apply to the repository
        description: Useful when testing new hooks to see if they apply to the repository
  - repo: local
    hooks:
      - id: prettier
        name: run prettier
        description: format files with prettier
        entry: prettier --write '**/*.html' '**/*.json' '**/*.md' '**/*.yaml' '**/*.yml'
        args: [--config=.github/linters/.prettierrc]
        files: \.(html|json|md|ya?ml)$
        language: node
        additional_dependencies: ['prettier@3.7.4']
      - id: check-zip-file-is-not-committed
        name: Zip files are not allowed in the repository
        description: Zip files are not allowed in the repository
        language: fail
        entry: |
          Zip files are not allowed in the repository as they are hard to
          track and have security implications. Please remove the zip file from the repository.
        files: \.zip$
  - repo: https://github.com/psf/black
    rev: 25.1.0
    hooks:
      - id: black
        name: The uncompromising Python code formatter
        description: Black is the uncompromising Python code formatter.
        types: [python]
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: check-case-conflict
        description: Check for files with names that would conflict on a case-insensitive filesystem like MacOS HFS+ or Windows FAT.
      - id: check-illegal-windows-names
        description: Check for files that cannot be created on Windows.
      - id: check-json
        description: Attempts to load all json files to verify syntax.
      - id: check-merge-conflict
        description: Check for files that contain merge conflict strings.
      - id: check-vcs-permalinks
        description: Ensures that links to vcs websites are permalinks.
      - id: check-yaml
        description: Attempts to load all yaml files to verify syntax.
      - id: detect-aws-credentials
        description: Checks for the existence of AWS secrets that you have set up with the AWS CLI.
        args: [--allow-missing-credentials]
      - id: detect-private-key
        description: Checks for the existence of private keys.
      - id: end-of-file-fixer
        description: Makes sure files end in a newline and only a newline.
      - id: fix-byte-order-marker
        description: Removes UTF-8 byte order marker.
      - id: forbid-submodules
        description: Forbids any submodules in the repository.
      - id: mixed-line-ending
        description: Replaces or checks mixed line ending.
      - id: trailing-whitespace
        description: Trims trailing whitespace.
  - repo: https://github.com/Lucas-C/pre-commit-hooks
    rev: v1.5.5
    hooks:
      - id: chmod
        name: Set file permissions
        description: Does not run on Windows so setup as a manual hook
        args: ['644']
        files: \.md$
        stages: [manual]
  - repo: https://github.com/pre-commit/pygrep-hooks
    rev: v1.10.0
    hooks:
      - id: python-check-mock-methods
        name: run check for not-real mock methods
        description: Prevent common mistakes of assert mck.not_called(), assert mck.called_once_with(...) and mck.assert_called
      - id: python-no-eval
        name: run check for eval()
        description: A quick check for the eval() built-in function
      - id: python-no-log-warn
        name: run check for use logger.warning(
        description: A quick check for the deprecated .warn() method of python loggers
      - id: python-use-type-annotations
        name: run check for type annotations not comments
        description: Enforce that python3.6+ type annotations are used instead of type comments
      - id: rst-backticks
        name: run rst-backticks
        description: detect common mistake of using single backticks when writing rst
      - id: rst-directive-colons
        name: run rst-directive-colons
        description: detect mistake of rst directive not ending with double colon or space before the double colon
      - id: rst-inline-touching-normal
        name: run rst-inline-touching-normal
        description: detect mistake of inline code touching normal text in rst
      - id: text-unicode-replacement-char
        name: run check for no unicode replacement char
        description: Forbid files which have a UTF-8 Unicode replacement character
  - repo: https://github.com/igorshubovych/markdownlint-cli
    rev: v0.45.0
    hooks:
      - id: markdownlint
        name: run markdownlint
        description: checks the style of Markdown files
        args: [--config=.github/linters/.markdown-lint.yml]
        types: [markdown]
        files: \.md$
  - repo: https://github.com/adrienverge/yamllint
    rev: v1.37.1
    hooks:
      - id: yamllint
        name: run yamllint
        description: check YAML files with yamllint
        args: [--strict, -c=.github/linters/.yaml-lint.yml]
        types: [yaml]
        files: \.ya?ml$
