# https://github.com/super-linter/super-linter
---
name: Super-Linter

"on":
  push:
    branches:
      # - main
      # - master
  pull_request:
    branches:
      - main

permissions:
  contents: read

jobs:
  build:
    name: ðŸ§¹ðŸª£ Lint Code Base
    runs-on: ubuntu-latest
    permissions:
      contents: read  # for actions/checkout to fetch code
      statuses: write  # for super-linter to mark status of each linter run
      packages: read  # To fetch super-linter/super-linter from ghcr.io
    steps:
      - name: 'Checkout ${{ github.ref }} ( ${{ github.sha }} )'
        uses: actions/checkout@v6
        with:
          # Full git history is needed to get proper list of changed files
          fetch-depth: 0
      - name: Lint Code Base
        uses: super-linter/super-linter@v8.3.1
        env:
          DEFAULT_BRANCH: main
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          VALIDATE_ALL_CODEBASE: true
